# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _words
else:
    import _words

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _words.delete_SwigPyIterator

    def value(self):
        return _words.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _words.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _words.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _words.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _words.SwigPyIterator_equal(self, x)

    def copy(self):
        return _words.SwigPyIterator_copy(self)

    def next(self):
        return _words.SwigPyIterator_next(self)

    def __next__(self):
        return _words.SwigPyIterator___next__(self)

    def previous(self):
        return _words.SwigPyIterator_previous(self)

    def advance(self, n):
        return _words.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _words.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _words.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _words.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _words.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _words.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _words.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _words:
_words.SwigPyIterator_swigregister(SwigPyIterator)

class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _words.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _words.StringVector___nonzero__(self)

    def __bool__(self):
        return _words.StringVector___bool__(self)

    def __len__(self):
        return _words.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _words.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _words.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _words.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _words.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _words.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _words.StringVector___setitem__(self, *args)

    def pop(self):
        return _words.StringVector_pop(self)

    def append(self, x):
        return _words.StringVector_append(self, x)

    def empty(self):
        return _words.StringVector_empty(self)

    def size(self):
        return _words.StringVector_size(self)

    def swap(self, v):
        return _words.StringVector_swap(self, v)

    def begin(self):
        return _words.StringVector_begin(self)

    def end(self):
        return _words.StringVector_end(self)

    def rbegin(self):
        return _words.StringVector_rbegin(self)

    def rend(self):
        return _words.StringVector_rend(self)

    def clear(self):
        return _words.StringVector_clear(self)

    def get_allocator(self):
        return _words.StringVector_get_allocator(self)

    def pop_back(self):
        return _words.StringVector_pop_back(self)

    def erase(self, *args):
        return _words.StringVector_erase(self, *args)

    def __init__(self, *args):
        _words.StringVector_swiginit(self, _words.new_StringVector(*args))

    def push_back(self, x):
        return _words.StringVector_push_back(self, x)

    def front(self):
        return _words.StringVector_front(self)

    def back(self):
        return _words.StringVector_back(self)

    def assign(self, n, x):
        return _words.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _words.StringVector_resize(self, *args)

    def insert(self, *args):
        return _words.StringVector_insert(self, *args)

    def reserve(self, n):
        return _words.StringVector_reserve(self, n)

    def capacity(self):
        return _words.StringVector_capacity(self)
    __swig_destroy__ = _words.delete_StringVector

# Register StringVector in _words:
_words.StringVector_swigregister(StringVector)


def new_string_ptr():
    return _words.new_string_ptr()

def copy_string_ptr(value):
    return _words.copy_string_ptr(value)

def delete_string_ptr(obj):
    return _words.delete_string_ptr(obj)

def string_ptr_assign(obj, value):
    return _words.string_ptr_assign(obj, value)

def string_ptr_value(obj):
    return _words.string_ptr_value(obj)
class Prefixer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, arg2):
        _words.Prefixer_swiginit(self, _words.new_Prefixer(arg2))
    __swig_destroy__ = _words.delete_Prefixer

    def set_prefix(self, arg2):
        return _words.Prefixer_set_prefix(self, arg2)

    def prefix(self):
        return _words.Prefixer_prefix(self)

    def preview(self, arg2):
        return _words.Prefixer_preview(self, arg2)

    def modify_word(self, arg2):
        return _words.Prefixer_modify_word(self, arg2)

    def modify_words(self, arg2):
        return _words.Prefixer_modify_words(self, arg2)

# Register Prefixer in _words:
_words.Prefixer_swigregister(Prefixer)


def one_shot(prefix, word):
    return _words.one_shot(prefix, word)


